function net = trainUNet_FixedPrior(segDS)

inputSize = [256 256 4];
numClasses = 2;

lgraph = unetLayers(inputSize, numClasses, 'EncoderDepth', 4);

classWeights = [1.0, 3.0];

pxLayer = pixelClassificationLayer( ...
    'Name', 'Segmentation-Layer', ...
    'Classes', segDS.classes, ...
    'ClassWeights', classWeights);

lgraph = replaceLayer(lgraph, 'Segmentation-Layer', pxLayer);

options = trainingOptions('adam', ...
    'InitialLearnRate', 1e-4, ...
    'MaxEpochs', 80, ...
    'MiniBatchSize', 8, ...
    'Shuffle', 'every-epoch', ...
    'ValidationData', segDS.physics.val, ...
    'ValidationFrequency', 10, ...
    'Verbose', false, ...
    'Plots', 'training-progress');

net = trainNetwork(segDS.physics.train, lgraph, options);

end