function net = trainStage1_ResNet(splits, inputSize)

imdsTrain = imageDatastore(splits.stage1.trainFiles);
imdsTrain.Labels = splits.stage1.trainLabels;

imdsVal = imageDatastore(splits.stage1.valFiles);
imdsVal.Labels = splits.stage1.valLabels;

augTrain = augmentedImageDatastore(inputSize(1:2), imdsTrain, ...
    'ColorPreprocessing', 'gray2rgb');

augVal = augmentedImageDatastore(inputSize(1:2), imdsVal, ...
    'ColorPreprocessing', 'gray2rgb');

lgraph = layerGraph(resnet18);

lgraph = replaceLayer(lgraph, 'fc1000', ...
    fullyConnectedLayer(2, ...
    'Name', 'new_fc', ...
    'WeightLearnRateFactor', 10, ...
    'BiasLearnRateFactor', 10));

lgraph = replaceLayer(lgraph, 'ClassificationLayer_predictions', ...
    classificationLayer('Name', 'new_classoutput'));

options = trainingOptions('adam', ...
    'InitialLearnRate', 1e-4, ...
    'MiniBatchSize', 16, ...
    'MaxEpochs', 10, ...
    'Shuffle', 'every-epoch', ...
    'ValidationData', augVal, ...
    'ValidationFrequency', 10, ...
    'Verbose', false, ...
    'Plots', 'training-progress');

net = trainNetwork(augTrain, lgraph, options);

end